/* eslint-disable */

(function () {/*

  Copyright The Closure Library Authors.
  SPDX-License-Identifier: Apache-2.0
 */
  var n = this || self, p = function (a, b) { a = a.split("."); var c = n; a[0] in c || "undefined" == typeof c.execScript || c.execScript("var " + a[0]); for (var d; a.length && (d = a.shift());)a.length || void 0 === b ? c = c[d] && c[d] !== Object.prototype[d] ? c[d] : c[d] = {} : c[d] = b }; var q = {}, r = function () { q.TAGGING = q.TAGGING || []; q.TAGGING[1] = !0 }; var t = function (a, b) { for (var c in b) b.hasOwnProperty(c) && (a[c] = b[c]) }, v = function (a) { for (var b in a) if (a.hasOwnProperty(b)) return !0; return !1 }; var x = /^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i; var y = window, z = document, A = function (a, b) { z.addEventListener ? z.addEventListener(a, b, !1) : z.attachEvent && z.attachEvent("on" + a, b) }; var B = /:[0-9]+$/, C = function (a, b, c) { a = a.split("&"); for (var d = 0; d < a.length; d++) { var e = a[d].split("="); if (decodeURIComponent(e[0]).replace(/\+/g, " ") === b) return b = e.slice(1).join("="), c ? b : decodeURIComponent(b).replace(/\+/g, " ") } }, F = function (a, b) {
    b && (b = String(b).toLowerCase()); if ("protocol" === b || "port" === b) a.protocol = D(a.protocol) || D(y.location.protocol); "port" === b ? a.port = String(Number(a.hostname ? a.port : y.location.port) || ("http" == a.protocol ? 80 : "https" == a.protocol ? 443 : "")) : "host" === b && (a.hostname = (a.hostname ||
      y.location.hostname).replace(B, "").toLowerCase()); return E(a, b, void 0, void 0, void 0)
  }, E = function (a, b, c, d, e) {
    var f = D(a.protocol); b && (b = String(b).toLowerCase()); switch (b) {
      case "url_no_fragment": d = ""; a && a.href && (d = a.href.indexOf("#"), d = 0 > d ? a.href : a.href.substr(0, d)); a = d; break; case "protocol": a = f; break; case "host": a = a.hostname.replace(B, "").toLowerCase(); c && (d = /^www\d*\./.exec(a)) && d[0] && (a = a.substr(d[0].length)); break; case "port": a = String(Number(a.port) || ("http" == f ? 80 : "https" == f ? 443 : "")); break; case "path": a.pathname ||
        a.hostname || r(); a = "/" == a.pathname.substr(0, 1) ? a.pathname : "/" + a.pathname; a = a.split("/"); a: if (d = d || [], c = a[a.length - 1], Array.prototype.indexOf) d = d.indexOf(c), d = "number" == typeof d ? d : -1; else { for (e = 0; e < d.length; e++)if (d[e] === c) { d = e; break a } d = -1 } 0 <= d && (a[a.length - 1] = ""); a = a.join("/"); break; case "query": a = a.search.replace("?", ""); e && (a = C(a, e, void 0)); break; case "extension": a = a.pathname.split("."); a = 1 < a.length ? a[a.length - 1] : ""; a = a.split("/")[0]; break; case "fragment": a = a.hash.replace("#", ""); break; default: a =
          a && a.href
    }return a
  }, D = function (a) { return a ? a.replace(":", "").toLowerCase() : "" }, G = function (a) { var b = z.createElement("a"); a && (b.href = a); var c = b.pathname; "/" !== c[0] && (a || r(), c = "/" + c); a = b.hostname.replace(B, ""); return { href: b.href, protocol: b.protocol, host: b.host, hostname: a, pathname: c, search: b.search, hash: b.hash, port: b.port } }; function H() { for (var a = I, b = {}, c = 0; c < a.length; ++c)b[a[c]] = c; return b } function J() { var a = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"; a += a.toLowerCase() + "0123456789-_"; return a + "." } var I, K;
  function aa(a) { function b(k) { for (; d < a.length;) { var m = a.charAt(d++), l = K[m]; if (null != l) return l; if (!/^[\s\xa0]*$/.test(m)) throw Error("Unknown base64 encoding at char: " + m); } return k } I = I || J(); K = K || H(); for (var c = "", d = 0; ;) { var e = b(-1), f = b(0), g = b(64), h = b(64); if (64 === h && -1 === e) return c; c += String.fromCharCode(e << 2 | f >> 4); 64 != g && (c += String.fromCharCode(f << 4 & 240 | g >> 2), 64 != h && (c += String.fromCharCode(g << 6 & 192 | h))) } }; var L; var N = function () { var a = ba, b = ca, c = M(), d = function (g) { a(g.target || g.srcElement || {}) }, e = function (g) { b(g.target || g.srcElement || {}) }; if (!c.init) { A("mousedown", d); A("keyup", d); A("submit", e); var f = HTMLFormElement.prototype.submit; HTMLFormElement.prototype.submit = function () { b(this); f.call(this) }; c.init = !0 } }, O = function (a, b, c, d, e) { a = { callback: a, domains: b, fragment: 2 === c, placement: c, forms: d, sameHost: e }; M().decorators.push(a) }, P = function (a, b, c) {
    for (var d = M().decorators, e = {}, f = 0; f < d.length; ++f) {
      var g = d[f], h; if (h =
        !c || g.forms) a: { h = g.domains; var k = a, m = !!g.sameHost; if (h && (m || k !== z.location.hostname)) for (var l = 0; l < h.length; l++)if (h[l] instanceof RegExp) { if (h[l].test(k)) { h = !0; break a } } else if (0 <= k.indexOf(h[l]) || m && 0 <= h[l].indexOf(k)) { h = !0; break a } h = !1 } h && (h = g.placement, void 0 == h && (h = g.fragment ? 2 : 1), h === b && t(e, g.callback()))
    } return e
  }, M = function () { var a = {}; var b = y.google_tag_data; y.google_tag_data = void 0 === b ? a : b; a = y.google_tag_data; b = a.gl; b && b.decorators || (b = { decorators: [] }, a.gl = b); return b }; var da = /(.*?)\*(.*?)\*(.*)/, ea = /([^?#]+)(\?[^#]*)?(#.*)?/; function Q(a) { return new RegExp("(.*?)(^|&)" + a + "=([^&]*)&?(.*)") }
  var S = function (a) { var b = [], c; for (c in a) if (a.hasOwnProperty(c)) { var d = a[c]; if (void 0 !== d && d === d && null !== d && "[object Object]" !== d.toString()) { b.push(c); var e = b, f = e.push; d = String(d); I = I || J(); K = K || H(); for (var g = [], h = 0; h < d.length; h += 3) { var k = h + 1 < d.length, m = h + 2 < d.length, l = d.charCodeAt(h), u = k ? d.charCodeAt(h + 1) : 0, w = m ? d.charCodeAt(h + 2) : 0, fa = l >> 2; l = (l & 3) << 4 | u >> 4; u = (u & 15) << 2 | w >> 6; w &= 63; m || (w = 64, k || (u = 64)); g.push(I[fa], I[l], I[u], I[w]) } f.call(e, g.join("")) } } a = b.join("*"); return ["1", R(a), a].join("*") }, R = function (a,
    b) { a = [window.navigator.userAgent, (new Date).getTimezoneOffset(), window.navigator.userLanguage || window.navigator.language, Math.floor((new Date).getTime() / 60 / 1E3) - (void 0 === b ? 0 : b), a].join("*"); if (!(b = L)) { b = Array(256); for (var c = 0; 256 > c; c++) { for (var d = c, e = 0; 8 > e; e++)d = d & 1 ? d >>> 1 ^ 3988292384 : d >>> 1; b[c] = d } } L = b; b = 4294967295; for (c = 0; c < a.length; c++)b = b >>> 8 ^ L[(b ^ a.charCodeAt(c)) & 255]; return ((b ^ -1) >>> 0).toString(36) }, ia = function (a) {
      return function (b) {
        var c = G(y.location.href), d = c.search.replace("?", ""); var e = C(d,
          "_gl", !0); b.query = T(e || "") || {}; e = F(c, "fragment"); var f = e.match(Q("_gl")); b.fragment = T(f && f[3] || "") || {}; a && ha(c, d, e)
      }
    }; function U(a, b) { if (a = Q(a).exec(b)) { var c = a[2], d = a[4]; b = a[1]; d && (b = b + c + d) } return b }
  var ha = function (a, b, c) { function d(f, g) { f = U("_gl", f); f.length && (f = g + f); return f } if (y.history && y.history.replaceState) { var e = Q("_gl"); if (e.test(b) || e.test(c)) a = F(a, "path"), b = d(b, "?"), c = d(c, "#"), y.history.replaceState({}, void 0, "" + a + b + c) } }, T = function (a) {
    var b = void 0 === b ? 3 : b; try {
      if (a) {
        a: { for (var c = 0; 3 > c; ++c) { var d = da.exec(a); if (d) { var e = d; break a } a = decodeURIComponent(a) } e = void 0 } if (e && "1" === e[1]) {
          var f = e[2], g = e[3]; a: { for (e = 0; e < b; ++e)if (f === R(g, e)) { var h = !0; break a } h = !1 } if (h) {
            b = {}; var k = g ? g.split("*") :
              []; for (g = 0; g < k.length; g += 2)b[k[g]] = aa(k[g + 1]); return b
          }
        }
      }
    } catch (m) { }
  }; function V(a, b, c, d) { function e(k) { k = U(a, k); var m = k.charAt(k.length - 1); k && "&" !== m && (k += "&"); return k + h } d = void 0 === d ? !1 : d; var f = ea.exec(c); if (!f) return ""; c = f[1]; var g = f[2] || ""; f = f[3] || ""; var h = a + "=" + b; d ? f = "#" + e(f.substring(1)) : g = "?" + e(g.substring(1)); return "" + c + g + f }
  function W(a, b) { var c = "FORM" === (a.tagName || "").toUpperCase(), d = P(b, 1, c), e = P(b, 2, c); b = P(b, 3, c); v(d) && (d = S(d), c ? X("_gl", d, a) : Y("_gl", d, a, !1)); !c && v(e) && (c = S(e), Y("_gl", c, a, !0)); for (var f in b) b.hasOwnProperty(f) && Z(f, b[f], a) } function Z(a, b, c, d) { if (c.tagName) { if ("a" === c.tagName.toLowerCase()) return Y(a, b, c, d); if ("form" === c.tagName.toLowerCase()) return X(a, b, c) } if ("string" == typeof c) return V(a, b, c, d) } function Y(a, b, c, d) { c.href && (a = V(a, b, c.href, void 0 === d ? !1 : d), x.test(a) && (c.href = a)) }
  function X(a, b, c) { if (c && c.action) { var d = (c.method || "").toLowerCase(); if ("get" === d) { d = c.childNodes || []; for (var e = !1, f = 0; f < d.length; f++) { var g = d[f]; if (g.name === a) { g.setAttribute("value", b); e = !0; break } } e || (d = z.createElement("input"), d.setAttribute("type", "hidden"), d.setAttribute("name", a), d.setAttribute("value", b), c.appendChild(d)) } else "post" === d && (a = V(a, b, c.action), x.test(a) && (c.action = a)) } }
  var ba = function (a) { try { a: { for (var b = 100; a && 0 < b;) { if (a.href && a.nodeName.match(/^a(?:rea)?$/i)) { var c = a; break a } a = a.parentNode; b-- } c = null } if (c) { var d = c.protocol; "http:" !== d && "https:" !== d || W(c, c.hostname) } } catch (e) { } }, ca = function (a) { try { if (a.action) { var b = F(G(a.action), "host"); W(a, b) } } catch (c) { } }; p("google_tag_data.glBridge.auto", function (a, b, c, d) { N(); O(a, b, "fragment" === c ? 2 : 1, !!d, !1) }); p("google_tag_data.glBridge.passthrough", function (a, b, c) { N(); O(a, [E(y.location, "host", !0)], b, !!c, !0) }); p("google_tag_data.glBridge.decorate", function (a, b, c) { a = S(a); return Z("_gl", a, b, !!c) }); p("google_tag_data.glBridge.generate", S); p("google_tag_data.glBridge.get", function (a, b) { var c = ia(!!b); b = M(); b.data || (b.data = { query: {}, fragment: {} }, c(b.data)); c = {}; if (b = b.data) t(c, b.query), a && t(c, b.fragment); return c });
})(window);
(function () {
  function ic(a) { var b = 1, c; if (a) for (b = 0, c = a.length - 1; 0 <= c; c--) { var d = a.charCodeAt(c); b = (b << 6 & 268435455) + d + (d << 14); d = b & 266338304; b = 0 != d ? b ^ d >> 21 : b } return b };/*

  Copyright The Closure Library Authors.
  SPDX-License-Identifier: Apache-2.0
 */
  var M; function Ga(a, b) { var c = [].slice.call(arguments); c.unshift("log"); M.log.apply(M, c) } function N(a, b) { var c = [].slice.call(arguments); c.unshift("info"); M.log.apply(M, c) } function J(a, b) { var c = [].slice.call(arguments); c.unshift("warn"); M.log.apply(M, c) } function O(a, b) { var c = [].slice.call(arguments); c.unshift("error"); M.log.apply(M, c) } function L(a, b) { var c = Q.ga_debug; c && c.trace && (c = [].slice.call(arguments), c.unshift("log"), M.log.apply(M, c)) }
  function dd(a, b) { var c = [].slice.call(arguments); c.unshift("group"); M.log.apply(M, c) } function ge() { M.log.apply(M, ["groupEnd"]) } M = new function () { var a = window.console, b = a && "Firebug Lite" == a.provider; this.log = function (c, d, e) { if (a) { var f = Ha.apply(window, [].slice.call(arguments, 1)); if (b) { f = f.split("\n"); for (var ea = 0; ea < f.length; ea++)a[c](f[ea]) } else if (a[c]) a[c](f); else "group" == c && a.log(f) } } };
  function Fa(a, b) { b = b || 0; if (void 0 == a) return "" + a; if (G(a)) return '"' + a + '"'; if (t(a)) return "[function]"; if (sa(a)) { if (3 < b) return "[...]"; for (var c = [], d = 0; d < a.length; d++)c.push(Fa(a[d], b + 1)); return "[" + c.join(", ") + "]" } if (a.constructor == Object) { if (3 < b) return "{...}"; c = []; for (d in a) c.push(d + ": " + Fa(a[d], b + 1)); return "{" + c.join(", ") + "}" } return "" + a } function Ha(a, b) { if (!G(a)) return ""; for (var c = a.split("%s"), d = 1; d < arguments.length; d++)c.splice(2 * d - 1, 0, Fa(arguments[d])); return c.join("") }; var ec = function (a) { this.B = a || [] }; ec.prototype.set = function (a) { this.B[a] = !0 }; ec.prototype.encode = function () { for (var a = [], b = 0; b < this.B.length; b++)this.B[b] && (a[Math.floor(b / 6)] ^= 1 << b % 6); for (b = 0; b < a.length; b++)a[b] = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_".charAt(a[b] || 0); return a.join("") + "~" }; var ca = window.GoogleAnalyticsObject, ka; if (ka = void 0 != ca) ka = -1 < (ca.constructor + "").indexOf("String"); var wa; if (wa = ka) { var Ba = window.GoogleAnalyticsObject; wa = Ba ? Ba.replace(/^[\s\xa0]+|[\s\xa0]+$/g, "") : "" } var Fc = wa || "ga", Bd = /^(?:utma\.)?\d+\.\d+$/, Cd = /^amp-[\w.-]{22,64}$/, $b = !1; var Ne = new ec; function F(a) { Ne.set(a) } var cf = function (a) { a = $e(a); a = new ec(a); for (var b = Ne.B.slice(), c = 0; c < a.B.length; c++)b[c] = b[c] || a.B[c]; return (new ec(b)).encode() }, $e = function (a) { a = a.get(af); sa(a) || (a = []); return a }; var t = function (a) { return "function" == typeof a }, sa = function (a) { return "[object Array]" == Object.prototype.toString.call(Object(a)) }, G = function (a) { return void 0 != a && -1 < (a.constructor + "").indexOf("String") }, H = function (a, b) { return 0 == a.indexOf(b) }, xa = function (a) { return a ? a.replace(/^[\s\xa0]+|[\s\xa0]+$/g, "") : "" }, ia = function () {
    for (var a = Q.navigator.userAgent + (I.cookie ? I.cookie : "") + (I.referrer ? I.referrer : ""), b = a.length, c = Q.history.length; 0 < c;)a += c-- ^ b++; return [ae() ^ ic(a) & 2147483647, Math.round((new Date).getTime() /
      1E3)].join(".")
  }, za = function (a) { var b = I.createElement("img"); b.width = 1; b.height = 1; b.src = a; return b }, Aa = function () { }, P = function (a) { if (encodeURIComponent instanceof Function) return encodeURIComponent(a); F(28); return a }, Ca = function (a, b, c, d) { try { a.addEventListener ? a.addEventListener(b, c, !!d) : a.attachEvent && a.attachEvent("on" + b, c) } catch (e) { F(27) } }, g = /^[\w\-:/.?=&%!\[\]]+$/, Fb = /^[\w+/_-]+[=]{0,2}$/, Vf = null, ye = function (a, b, c, d, e) {
    if (!Vf) {
      Vf = { createScriptURL: function (ea) { return ea }, createHTML: function (ea) { return ea } };
      try { Vf = window.trustedTypes.createPolicy("google-analytics", Vf) } catch (ea) { }
    } if (a) {
      N("Loading script: %s", a); var f = I.querySelector && I.querySelector("script[nonce]") || null; f = f ? f.nonce || f.getAttribute && f.getAttribute("nonce") || "" : ""; c ? (e = d = "", b && (g.test(b) ? d = ' id="' + b + '"' : J("Dropping invalid script ID: %s", b)), f && Fb.test(f) && (e = ' nonce="' + f + '"'), g.test(a) ? I.write(Vf.createHTML("<script" + d + e + ' src="' + a + '">\x3c/script>')) : J("URL uses invalid characters. Dropping request for: %s", a)) : (c = I.createElement("script"),
        c.type = "text/javascript", c.async = !0, c.src = Vf.createScriptURL(a), d && (c.onload = d), e && (c.onerror = e), b && (c.id = b), f && c.setAttribute("nonce", f), a = I.getElementsByTagName("script")[0], a.parentNode.insertBefore(c, a))
    }
  }, ee = function (a, b) { return aa(I.location[b ? "href" : "search"], a) }, aa = function (a, b) { return (a = a.match("(?:&|#|\\?)" + P(b).replace(/([.*+?^=!:${}()|\[\]\/\\])/g, "\\$1") + "=([^&#]*)")) && 2 == a.length ? a[1] : "" }, Wb = function () { var a = "" + I.location.hostname; return 0 == a.indexOf("www.") ? a.substring(4) : a }, Be = function (a,
    b) { var c = a.indexOf(b); if (5 == c || 6 == c) if (a = a.charAt(c + b.length), "/" == a || "?" == a || "" == a || ":" == a) return !0; return !1 }, Yb = function (a, b) { if (1 == b.length && null != b[0] && "object" === typeof b[0]) return b[0]; for (var c = {}, d = Math.min(a.length + 1, b.length), e = 0; e < d; e++)if ("object" === typeof b[e]) { for (var f in b[e]) b[e].hasOwnProperty(f) && (c[f] = b[e][f]); break } else e < a.length ? c[a[e]] = b[e] : J("Unrecognized positional argument: " + b[e]); return c }, Zb = function (a, b) { for (var c = 0; c < a.length; c++)if (b == a[c]) return !0; return !1 }; var ef = function () { this.ua = []; this.ia = {}; this.u = {}; this.debug = !1 }; ef.prototype.set = function (a, b, c) { this.debug && L("  " + a + "=" + Fa(b) + (c ? " (temp)" : "")); this.ua.push(a); c ? this.u[":" + a] = b : this.ia[":" + a] = b }; ef.prototype.get = function (a) { return this.u.hasOwnProperty(":" + a) ? this.u[":" + a] : this.ia[":" + a] }; ef.prototype.map = function (a) { for (var b = 0; b < this.ua.length; b++) { var c = this.ua[b], d = this.get(c); d && a(c, d) } }; var Rd = [{ V: "pa", W: "ec:action" }, { V: "ti", W: "ec:id" }, { V: "ta", W: "ec:affiliation" }, { V: "tr", W: "ec:revenue" }, { V: "tt", W: "ec:tax" }, { V: "ts", W: "ec:shipping" }, { V: "tcc", W: "ec:coupon" }, { V: "cos", W: "ec:step" }, { V: "col", W: "ec:label" }, { V: "pal", W: "ec:product action list" }, { V: "promoa", W: "ec:promo action" }, { V: /^pr(\d+)id$/, W: "ec:product %s id" }, { V: /^pr(\d+)nm$/, W: "ec:product %s name" }, { V: /^pr(\d+)br$/, W: "ec:product %s brand" }, { V: /^pr(\d+)ca$/, W: "ec:product %s category" }, { V: /^pr(\d+)va$/, W: "ec:product %s variant" }, {
      V: /^pr(\d+)ps$/,
      W: "ec:product %s position"
    }, { V: /^pr(\d+)pr$/, W: "ec:product %s price" }, { V: /^pr(\d+)qt$/, W: "ec:product %s quantity" }, { V: /^pr(\d+)cc$/, W: "ec:product %s coupon" }, { V: /^pr(\d+)cd(\d+)$/, W: "ec:product %s dimension %s" }, { V: /^pr(\d+)cm(\d+)$/, W: "ec:product %s metric %s" }, { V: /^promo(\d+)id$/, W: "ec:promo %s id" }, { V: /^promo(\d+)nm$/, W: "ec:promo %s name" }, { V: /^promo(\d+)cr$/, W: "ec:promo %s creative" }, { V: /^promo(\d+)ps$/, W: "ec:promo %s position" }, { V: /^il(\d+)nm$/, W: "ec:impression list %s name" }, {
      V: /^il(\d+)ls$/,
      W: "ec:impression list %s source"
    }, { V: /^il(\d+)pi(\d+)id$/, W: "ec:impression list %s product %s id" }, { V: /^il(\d+)pi(\d+)nm$/, W: "ec:impression list %s product %s name" }, { V: /^il(\d+)pi(\d+)br$/, W: "ec:impression list %s product %s brand" }, { V: /^il(\d+)pi(\d+)ca$/, W: "ec:impression list %s product %s category" }, { V: /^il(\d+)pi(\d+)va$/, W: "ec:impression list %s product %s variant" }, { V: /^il(\d+)pi(\d+)ps$/, W: "ec:impression list %s product %s position" }, { V: /^il(\d+)pi(\d+)pr$/, W: "ec:impression list %s product %s price" },
    { V: /^il(\d+)pi(\d+)cd(\d+)$/, W: "ec:impression list %s product %s dimension %s" }, { V: /^il(\d+)pi(\d+)cm(\d+)$/, W: "ec:impression list %s product %s metric %s" }, { V: "linkid", W: "linkid:linkId" }, { V: "ic", W: "ec:item code" }, { V: "in", W: "ec:item name" }, { V: "iv", W: "ec:item variation" }, { V: "ip", W: "ec:item price" }, { V: "iq", W: "ec:item quantity" }, { V: "cu", W: "ec:item currency" }], Sd = function (a) {
      "&" == a.charAt(0) && (a = a.substring(1)); for (var b = 0; b < Rd.length; b++) {
        var c = Rd[b].V, d = Rd[b].W; if (G(c)) { if (c == a) return d } else if (c = a.match(c)) return c[0] =
          d, Ha.apply(void 0, c)
      } return ""
    }; function Wf() { return 0 == Z.h ? -1 : (new Date).getTime() - Z.h } function Ia(a) { N("\nSent beacon:\n" + a + "\n\n"); var b = []; a = a.split("&"); for (var c = 0; c < a.length; c++) { var d = a[c].split("="), e = d[0], f = d[1]; if ("_" != e.charAt(0)) { var ea = kd(e); ea && 0 == ea.indexOf("&") && (ea = Sd(ea) || ea); if (ea) { "&" + e == ea && (ea = "<unknown>"); d = b; var l = d.push; e = "(&" + e + ")"; a: { f = f.split("+").join(" "); if (decodeURIComponent instanceof Function) try { var k = decodeURIComponent(f); break a } catch (v) { F(18) } F(28); k = f } l.call(d, [ea, e, k]) } } } b.sort(); Xd(b) }
  function Xd(a) { for (var b = [], c = 0; c < a.length; c++)for (var d = 0; d < a[c].length - 1; d++)a[c][d] && (b[d] = b[d] || 0, b[d] = a[c][d].length > b[d] ? a[c][d].length : b[d]); for (c = 0; c < a.length; c++) { var e = []; for (d = 0; d < a[c].length; d++) { var f = he(0) + a[c][d]; e.push(f + he((b[d] || 0) - f.length)) } N(e.join(" ")) } } function Ja(a) { var b = []; nf.map(function (e, f) { var ea = a.get(e); void 0 != ea && "_" != e[0] && b.push(e + (f.i ? " (" + f.i + ")" : "") + " = " + Fa(ea)) }); for (var c = b.sort(), d = 0; d < c.length; d++)N("  " + c[d]) }
  function Td(a) { for (var b in a) a.hasOwnProperty(b) && (Zb(ac, b) || (yc(b) ? J('This field cannot be set in a create method. Please use ga("set", %s, %s);', b, a[b]) : J("Create config had an unknown parameter: %s", b)), La(b, a[b])) } function he(a) { return 0 < a ? Array(a + 1).join(" ") : "" }
  function La(a, b) {
    if (void 0 == b) switch (a) { case U: case Ma: case Gc: J("Expected a value for required field: %s", a) } else {
      switch (a) {
        case Ma: case Na: case Oa: case Pa: case Qa: case Ra: case Sa: case Ta: case Ua: case Va: case Wa: case Xa: case Ya: case Za: case R: case $a: case ab: case bb: case cb: case db: case eb: case fb: case gb: case hb: case ib: case jb: case kb: case lb: case mb: case nb: case pb: case qb: case rb: case sb: case tb: case ub: case S: case vb: case wb: case xb: case Pd: G(b) || J("Expected a string value for field: %s. But found: %s.",
          a, typeof b); break; case yb: case zb: case Bb: case Cb: case Db: case Eb: !isNaN(parseFloat(b)) && isFinite(b) || J("Expected a number value for the field: %s. But found: %s.", a, typeof b); break; case Ab: isFinite(b) && !isNaN(parseInt(b, 10)) && -1 === String(b).indexOf(".") || J("Expected an integer value for the field: %s. But found: %s.", a, b); break; case Gb: case Ib: case Jb: case "forceSSL": case Kb: case Lb: case Mb: !0 !== b && !1 !== b && 1 !== b && 0 !== b && J("Expected a boolean value for the field: %s. But found: %s.", a, typeof b); break;
        case Nb: case Ob: case Pb: case Qb: case Rb: case Tb: case Ub: case Vb: t(b) || J("Expected a function for the field value: %s. But found: %s.", a, typeof b); break; case T: /^[a-zA-Z0-9_]+$/.test(b) || O("Tracker name should only consist of alphanumeric characters."); break; case U: va.test(b) || J("The tracking Id should only be of the format UA-NNNNNN-N."); break; case Hb: "start" != b && "end" != b && J('Expected "start" or "end" for the field: %s. But found: %s', a, b)
      }!/^contentGroup[0-9]+$/.test(a) && !/^dimension[0-9]+$/.test(a) ||
        G(b) || J("Expected a string value for field: %s. but found: %s.", a, typeof b); !/^metric[0-9]+$/.test(a) || !isNaN(parseFloat(b)) && isFinite(b) || J("Expected a number value for field: %s. but found: %s.", a, typeof b)
    }
  }
  function Ec(a) { function b(d) { G(a.get(d)) || O("Missing required field '%s' for hit of type '%s'", d, c) } var c = V(a, Ma); switch (c) { case "pageview": b(Pa); break; case "event": b(fb); b(gb); break; case "social": b(ib); b(jb); b(kb); break; case "exception": b(tb); break; case "timing": if (a.get(Ic)) break; b(lb); b(mb); break; case "appview": b(pb) } } var tc = ["__utma", "__utmb", "__utmz", "__utmv"]; var Q = window, I = document, ta = function (a, b) { return setTimeout(a, b) }; var Ka = window, xc = document, K = function (a) {
    var b = Ka._gaUserPrefs; if (b && b.ioo && b.ioo() || a && !0 === Ka["ga-disable-" + a]) return !0; try { var c = Ka.external; if (c && c._gaUserPrefs && "oo" == c._gaUserPrefs) return !0 } catch (f) { } a = []; b = String(xc.cookie).split(";"); for (c = 0; c < b.length; c++) { var d = b[c].split("="), e = d[0].replace(/^\s*|\s*$/g, ""); e && "AMP_TOKEN" == e && ((d = d.slice(1).join("=").replace(/^\s*|\s*$/g, "")) && (d = decodeURIComponent(d)), a.push(d)) } for (b = 0; b < a.length; b++)if ("$OPT_OUT" == a[b]) return !0; return xc.getElementById("__gaOptOutExtension") ?
      !0 : !1
  }; var Md = function (a) { var b = [], c = I.cookie.split(";"); a = new RegExp("^\\s*" + a + "=\\s*(.*?)\\s*$"); for (var d = 0; d < c.length; d++) { var e = c[d].match(a); e && b.push(e[1]) } return b }, pe = function (a, b, c, d, e, f, ea) {
    K(e) ? ("function" == typeof N && N("Aborting cookie write: User has opted out of tracking."), e = !1) : Wd.test(I.location.hostname) || "/" == c && fe.test(d) ? ("function" == typeof N && N("Aborting cookie write: Prohibited domain."), e = !1) : e = !0; if (!e) return !1; b && 1200 < b.length && (b = b.substring(0, 1200)); c = a + "=" + b + "; path=" + c + "; ";
    f && (c += "expires=" + (new Date((new Date).getTime() + f)).toGMTString() + "; "); d && "none" !== d && (c += "domain=" + d + ";"); ea && (c += ea + ";"); d = I.cookie; I.cookie = c; if (!(d = d != I.cookie)) a: { a = Md(a); for (d = 0; d < a.length; d++)if (b == a[d]) { d = !0; break a } d = !1 } return d
  }, Ae = function (a) { return encodeURIComponent ? encodeURIComponent(a).replace(/\(/g, "%28").replace(/\)/g, "%29") : a }, fe = /^(www\.)?google(\.com?)?(\.[a-z]{2})?$/, Wd = /(^|\.)doubleclick\.net$/i; var Dc = function (a) { var b = [], c = I.cookie.split(";"); a = new RegExp("^\\s*" + (a || "_gac") + "_(UA-\\d+-\\d+)=\\s*(.+?)\\s*$"); for (var d = 0; d < c.length; d++) { var e = c[d].match(a); e && b.push({ ma: e[1], value: e[2], timestamp: Number(e[2].split(".")[1]) || 0 }) } b.sort(function (f, ea) { return ea.timestamp - f.timestamp }); return b };
  function Lf(a, b, c) { b = Dc(b); var d = {}; if (!b || !b.length) return d; for (var e = 0; e < b.length; e++) { var f = b[e].value.split("."); if ("1" !== f[0] || c && 3 > f.length || !c && 3 !== f.length) a && (a.qa = !0); else if (Number(f[1])) { d[b[e].ma] ? a && (a.sa = !0) : d[b[e].ma] = []; var ea = { version: f[0], timestamp: 1E3 * Number(f[1]), ta: f[2] }; c && 3 < f.length && (ea.labels = f.slice(3)); d[b[e].ma].push(ea) } } return d }; var Da, Sb, cc, dc, ma = /^https?:\/\/[^/]*cdn\.ampproject\.org\//, Nf = /^(?:www\.|m\.|amp\.)+/, sc = [], fa = function (a) {
    if (rf(a[ce])) { if (void 0 === dc) { var b; if (b = (b = wf.get()) && b._ga || void 0) dc = b, F(81) } if (void 0 !== dc) return a[R] ? J("Using client id from config instead of AMP.") : (N("Using client id Provided by AMP."), a[R] = dc), !1 } if (a[ce]) {
      F(67); if (a[xb] && "cookie" != a[xb]) return J("Can't use AMP client id when storage is not 'cookie'."), !1; if (void 0 !== dc) a[R] ? J("Using client id from config instead of AMP.") : a[R] =
        dc; else { a: { b = String(a[S] || Wb()); var c = String(a[vb] || "/"), d = Md(String(a[ub] || "_ga")); b = pa(d, b, c); if (!b || Bd.test(b)) b = !0; else if (b = Md("AMP_TOKEN"), 0 == b.length) b = !0; else { if (1 == b.length && (b = decodeURIComponent(b[0]), "$RETRIEVING" == b || "$OPT_OUT" == b || "$ERROR" == b || "$NOT_FOUND" == b)) { b = !0; break a } b = !1 } } if (b) { if ($c(Uc, String(a[U]))) return N("Requesting client id from AMP."), !0; J("Could not request client id from AMP.") } }
    } return !1
  }, Uc = function () { jf.H([Aa]) }, $c = function (a, b) {
    var c = Md("AMP_TOKEN"); if (1 < c.length) return F(55),
      !1; c = decodeURIComponent(c[0] || ""); if ("$OPT_OUT" == c || "$ERROR" == c || K(b)) return F(62), !1; if (!ma.test(I.referrer) && "$NOT_FOUND" == c) return F(68), !1; if (void 0 !== dc) return F(56), ta(function () { a(dc) }, 0), !0; if (Da) return sc.push(a), !0; if ("$RETRIEVING" == c) return F(57), ta(function () { $c(a, b) }, 1E4), !0; Da = !0; c && "$" != c[0] || (ed("$RETRIEVING", 3E4), setTimeout(jd, 3E4), c = ""); return ld(c, b) ? (sc.push(a), !0) : !1
  }, ld = function (a, b, c) {
    if (!window.JSON) return F(58), !1; var d = Q.XMLHttpRequest; if (!d) return F(59), !1; var e = new d; if (!("withCredentials" in
      e)) return F(60), !1; e.open("POST", (c || "https://ampcid.google.com/v1/publisher:getClientId") + "?key=AIzaSyA65lEHUEizIsNtlbNo-l2K18dT680nsaM", !0); e.withCredentials = !0; e.setRequestHeader("Content-Type", "text/plain"); e.onload = function () {
        Da = !1; if (4 == e.readyState) {
          try {
            200 != e.status && (J("Could not get client id from AMP."), F(61), yd("", "$ERROR", 3E4)); var f = JSON.parse(e.responseText); f.optOut ? (J("Could not get client id from AMP. User has opeted out."), F(63), yd("", "$OPT_OUT", 31536E6)) : f.clientId ? (N("Got client id from AMP."),
              yd(f.clientId, f.securityToken, 31536E6)) : !c && f.alternateUrl ? (N("Got an alternate URL to get client id."), Sb && clearTimeout(Sb), Da = !0, ld(a, b, f.alternateUrl)) : (J("Could not get client id from AMP."), F(64), yd("", "$NOT_FOUND", 36E5))
          } catch (ea) { J("Could not get client id from AMP."), F(65), yd("", "$ERROR", 3E4) } e = null
        }
      }; d = { originScope: "AMP_ECID_GOOGLE" }; a && (d.securityToken = a); e.send(JSON.stringify(d)); Sb = ta(function () { F(66); yd("", "$ERROR", 3E4) }, 1E4); return !0
  }, jd = function () { Da = !1 }, ed = function (a, b) {
    if (void 0 ===
      cc) { cc = ""; for (var c = fd(), d = 0; d < c.length; d++) { var e = c[d]; if (pe("AMP_TOKEN", encodeURIComponent(a), "/", e, "", b)) { cc = e; return } } } pe("AMP_TOKEN", encodeURIComponent(a), "/", cc, "", b)
  }, yd = function (a, b, c) { Sb && clearTimeout(Sb); b && ed(b, c); dc = a; b = sc; sc = []; for (c = 0; c < b.length; c++)b[c](a) }, rf = function (a) {
    a: {
      if (ma.test(I.referrer)) {
        var b = I.location.hostname.replace(Nf, ""); b: {
          var c = I.referrer; c = c.replace(/^https?:\/\//, ""); var d = c.replace(/^[^/]+/, "").split("/"), e = d[2]; d = (d = "s" == e ? d[3] : e) ? decodeURIComponent(d) : d; if (!d) {
            if (0 ==
              c.indexOf("xn--")) { J("IDN are not fully supported for AMP integration."); c = ""; break b } (c = c.match(/(.*)\.cdn\.ampproject\.org\/?$/)) && 2 == c.length && (d = c[1].replace(/-/g, ".").replace(/\.\./g, "-"))
          } c = d ? d.replace(Nf, "") : ""
        } (d = b === c) || (c = "." + c, d = b.substring(b.length - c.length, b.length) === c); if (d) { b = !0; break a } else F(78)
      } b = !1
    } return b && !1 !== a
  }; var Od = function (a) { return (a ? "https:" : $b || "https:" == I.location.protocol ? "https:" : "http:") + "//www.google-analytics.com" }, zf = function (a) { switch (a) { default: O("Container plugin URL requested without an explicit type."); case 1: return "https://www.google-analytics.com/gtm/js?id="; case 2: return "https://www.googletagmanager.com/gtag/js?id=" } }, bc = function (a) { this.name = "len"; this.message = a + "-8192" }, da = function (a, b, c) {
    c = c || Aa; if (2036 >= b.length) id(a, b, c), Ia(b); else if (8192 >= b.length) u(a, b, c) || te(a, b, c) || id(a, b,
      c), Ia(b); else throw O("Payload size is too large (%s).  Max allowed is %s.", b.length, 8192), fc("len", b.length), new bc(b.length);
  }, hf = function (a, b, c, d) { d = d || Aa; te(a + "?" + b, "", d, c) && Ia(b) }, id = function (a, b, c) { var d = za(a + "?" + b); d.onload = d.onerror = function () { d.onload = null; d.onerror = null; c() } }, te = function (a, b, c, d) {
    var e = Q.XMLHttpRequest; if (!e) return !1; var f = new e; if (!("withCredentials" in f)) return !1; a = a.replace(/^http:/, "https:"); f.open("POST", a, !0); f.withCredentials = !0; f.setRequestHeader("Content-Type",
      "text/plain"); f.onreadystatechange = function () { if (4 == f.readyState) { if (d && "text/plain" === f.getResponseHeader("Content-Type")) try { Ea(d, f.responseText, c) } catch (ea) { fc("xhr", "rsp"), c() } else c(); f = null } }; f.send(b); return !0
  }, Ea = function (a, b, c) {
    if (1 > b.length) fc("xhr", "ver", "0"), c(); else if (3 < a.count++) fc("xhr", "tmr", "" + a.count), c(); else {
      var d = b.charAt(0); if ("1" === d) hd(a, b.substring(1), c); else if (a.Z && "2" === d) {
        var e = b.substring(1).split(","), f = 0; b = function () { ++f === e.length && c() }; for (d = 0; d < e.length; d++)hd(a,
          e[d], b)
      } else fc("xhr", "ver", String(b.length)), c()
    }
  }, hd = function (a, b, c) {
    if (0 === b.length) c(); else {
      var d = b.charAt(0); switch (d) {
        case "d": hf("https://stats.g.doubleclick.net/j/collect", a.Y, a, c); break; case "g": id("https://www.google.%/ads/ga-audiences".replace("%", "com"), a.google, c); (b = b.substring(1)) && (/^[a-z.]{1,6}$/.test(b) ? id("https://www.google.%/ads/ga-audiences".replace("%", b), a.google, Aa) : fc("tld", "bcc", b)); break; case "G": if (a.Z) { a.Z("G-" + b.substring(1)); c(); break } case "x": if (a.Z) { a.Z(); c(); break } default: fc("xhr",
          "brc", d), c()
      }
    }
  }, u = function (a, b, c) { return Q.navigator.sendBeacon ? Q.navigator.sendBeacon(a, b) ? (c(), !0) : !1 : !1 }, fc = function (a, b, c) { O("Error: type=%s method=%s message=%s account=%s", arguments); if (!(1 <= 100 * Math.random() || K("?"))) { var d = ["t=error", "_e=" + a, "_v=j91d", "sr=1"]; b && d.push("_f=" + b); c && d.push("_m=" + P(c.substring(0, 100))); d.push("aip=1"); d.push("z=" + ae()); id(Od(!0) + "/u/d", d.join("&"), Aa) } }; var bd = function () { return Q.gaData = Q.gaData || {} }, h = function (a) { var b = bd(); return b[a] = b[a] || {} }; var gc = function () { this.m = [] }; gc.prototype.add = function (a) { this.m.push(a) }; gc.prototype.H = function (a) { L("\nExecuting " + this.m.length + " filters:"); try { for (var b = 0; b < this.m.length; b++) { L("  filter[" + b + "]: " + this.m[b]); var c = a.get(this.m[b]); c && t(c) ? c.call(Q, a) : L("  Skipping (no function found.)") } } catch (d) { L("Aborted execution due to exception: " + d) } b = a.get(Nb); b != Aa && t(b) && (L("Manually firing callback"), a.set(Nb, Aa, !0), setTimeout(b, 10)) };
  function hc(a) { if (100 != a.get(Db) && ic(V(a, R)) % 1E4 >= 100 * jc(a, Db)) throw N("User has been sampled out. Aborting hit."), "abort"; } function kc(a) { if (K(V(a, U))) throw N("User has opted out of tracking. Aborting hit."), "abort"; } function lc() { var a = I.location.protocol; if ("http:" != a && "https:" != a) throw N("Unallowed document protocol. Aborting hit."), "abort"; }
  function mc(a) { try { Q.navigator.sendBeacon ? F(42) : Q.XMLHttpRequest && "withCredentials" in new Q.XMLHttpRequest && F(40) } catch (c) { } a.set(oc, cf(a), !0); a.set(md, jc(a, md) + 1); var b = []; nf.map(function (c, d) { d.i && (c = a.get(c), void 0 != c && c != d.defaultValue && ("boolean" == typeof c && (c *= 1), b.push(d.i + "=" + P("" + c)))) }); !1 === a.get(qf) && b.push("npa=1"); b.push("z=" + be()); a.set(Na, b.join("&"), !0) }
  function pc(a) {
    var b = V(a, ha); !b && a.get(Oe) && (b = "beacon"); var c = V(a, ob), d = V(a, bf), e = c || (d || Od(!1) + "") + "/collect"; switch (V(a, Nd)) {
      case "d": e = c || (d || Od(!1) + "") + "/j/collect"; b = a.get(kf) || void 0; hf(e, V(a, Na), b, a.v(Nb)); break; default: b ? (c = V(a, Na), d = a.v(Nb), 8192 < c.length && O("Payload size is too large (%s).  Max allowed is %s.", c.length, 8192), d = d || Aa, N("Sending hit with transport method %s", b), "image" == b ? (id(e, c, d), Ia(c)) : "xhr" == b && te(e, c, d) ? Ia(c) : "beacon" == b && u(e, c, d) ? Ia(c) : (N("Transport Method, %s, is not supported, falling back to default method.",
        b), da(e, c, d))) : da(e, V(a, Na), a.v(Nb))
    }e = V(a, U); e = h(e); b = e.hitcount; e.hitcount = b ? b + 1 : 1; e.first_hit || (e.first_hit = (new Date).getTime()); e = V(a, U); delete h(e).pending_experiments; a.set(Nb, Aa, !0)
  } function td(a) { bd().expId && a.set(zd, bd().expId); bd().expVar && a.set(Ad, bd().expVar); var b = V(a, U); if (b = h(b).pending_experiments) { var c = []; for (d in b) b.hasOwnProperty(d) && b[d] && c.push(encodeURIComponent(d) + "." + encodeURIComponent(b[d])); var d = c.join("!") } else d = void 0; d && ((b = a.get(m)) && (d = b + "!" + d), a.set(m, d, !0)) }
  function nc(a) { Ec(a) } function Ud() { if (Q.navigator && "preview" == Q.navigator.loadPurpose) throw N("Navigator in preview mode. Aborting hit."), "abort"; } function ve(a) { var b = Q.gaDevIds || []; if (sa(b)) { var c = a.get("&did"); G(c) && 0 < c.length && (b = b.concat(c.split(","))); c = []; for (var d = 0; d < b.length; d++)Zb(c, b[d]) || c.push(b[d]); 0 != c.length && a.set("&did", c.join(","), !0) } } function ya(a) { if (!a.get(U)) throw O("Tracking ID not set. Aborting hit."), "abort"; }
  function Qc(a) {
    try {
      if (!a.get(Ie) && (a.set(Ie, !0), !a.get("&gtm"))) {
        var b = !1, c = Q.location.search.split("?")[1]; c && Zb(c.split("&"), "gtm_debug=x") && (b = !0); !b && H(I.referrer, "https://tagassistant.google.com/") && (b = !0); !b && Zb(I.cookie.split("; "), "__TAG_ASSISTANT=x") && (b = !0); !b && Q.__TAG_ASSISTANT_API && (b = !0); if (b) {
          Q["google.tagmanager.debugui2.queue"] || (Q["google.tagmanager.debugui2.queue"] = [], ye("https://www.google-analytics.com/debug/bootstrap")); var d = I.currentScript; Q["google.tagmanager.debugui2.queue"].push({
            messageType: "LEGACY_CONTAINER_STARTING",
            data: { id: a.get(U), scriptSource: d && d.src || "" }
          }); J("Tag Assistant debug signal detected for unsupported legacy tag.")
        }
      }
    } catch (e) { L("Tag Assistant signal processing failed: " + e) }
  }; var ae = function () { return Math.round(2147483647 * Math.random()) }, be = function () { try { var a = new Uint32Array(1); Q.crypto.getRandomValues(a); return a[0] & 2147483647 } catch (b) { return ae() } }; function qc(a) { var b = jc(a, rc); 500 <= b && (F(15), N("Exceeded maximum number of hits for this page. Try reducing the number of hits being sent.")); var c = V(a, Ma); if ("transaction" != c && "item" != c) { c = jc(a, uc); var d = (new Date).getTime(), e = jc(a, vc); 0 == e && a.set(vc, d); e = Math.round(2 * (d - e) / 1E3); 0 < e && (c = Math.min(c + e, 20), a.set(vc, d)); if (0 >= c) throw N("Exceeded rate limit for sending hits. Aborting hit."), "abort"; a.set(uc, --c) } a.set(rc, ++b) }; var wc = function () { this.data = new ef; this.data.debug = !0 }; wc.prototype.get = function (a) { var b = yc(a), c = this.data.get(a); b && void 0 == c && (c = t(b.defaultValue) ? b.defaultValue() : b.defaultValue); return b && b.v ? b.v(this, a, c) : c }; var V = function (a, b) { a = a.get(b); return void 0 == a ? "" : "" + a }, jc = function (a, b) { a = a.get(b); return void 0 == a || "" === a ? 0 : Number(a) }; wc.prototype.v = function (a) { return (a = this.get(a)) && t(a) ? a : Aa };
  wc.prototype.set = function (a, b, c) { if (a) if ("object" == typeof a) for (var d in a) a.hasOwnProperty(d) && zc(this, d, a[d], c); else zc(this, a, b, c) }; var zc = function (a, b, c, d) { La(b, c); var e = yc(b); e && e.A ? e.A(a, b, c, d) : a.data.set(b, c, d); e || N("Set called on unknown field: %s.", b) }; var nf = new ef, of = [], Ac = function (a, b, c, d, e) { this.name = a; this.i = b; this.v = d; this.A = e; this.defaultValue = c }, yc = function (a) { var b = nf.get(a); if (!b) for (var c = 0; c < of.length; c++) { var d = of[c], e = d[0].exec(a); if (e) { L("Generating new model field for name: " + a); b = d[1](e); nf.set(b.name, b); break } } return b }, kd = function (a) { var b; nf.map(function (c, d) { d.i == a && (b = d) }); return b && b.name }, W = function (a, b, c, d, e) { a = new Ac(a, b, c, d, e); nf.set(a.name, a); return a.name }, Bc = function (a, b) { of.push([new RegExp("^" + a + "$"), b]) }, X = function (a,
    b, c) { return W(a, b, c, void 0, Cc) }, Cc = function (a, b) { O("Ignored attempt to update read-only property: " + b) }; var Gc = X("apiVersion", "v"), Hc = X("clientVersion", "_v"); W("anonymizeIp", "aip"); var yb = W("adSenseId", "a"), Ma = W("hitType", "t"), Nb = W("hitCallback"), Na = W("hitPayload"), Gb = W("nonInteraction", "ni"), Pd = W("currencyCode", "cu"); W("dataSource", "ds"); var Oe = W("useBeacon", void 0, !1), ha = W("transport"), Hb = W("sessionControl", "sc", ""); W("sessionGroup", "sg");
  var zb = W("queueTime", "qt"), md = W("_s", "_s"), Oa = W("screenName", "cd"), Pa = W("location", "dl", ""), Qa = W("referrer", "dr"), Ra = W("page", "dp", ""), Sa = W("hostname", "dh"), Ta = W("language", "ul"), Ua = W("encoding", "de"), Va = W("title", "dt", function () { return I.title || void 0 }); Bc("contentGroup([0-9]+)", function (a) { return new Ac(a[0], "cg" + a[1]) });
  var Wa = W("screenColors", "sd"), Xa = W("screenResolution", "sr"), Ya = W("viewportSize", "vp"), Ib = W("javaEnabled", "je"), Za = W("flashVersion", "fl"), $a = W("campaignId", "ci"), ab = W("campaignName", "cn"), bb = W("campaignSource", "cs"), cb = W("campaignMedium", "cm"), db = W("campaignKeyword", "ck"), eb = W("campaignContent", "cc"), fb = W("eventCategory", "ec"), gb = W("eventAction", "ea"), hb = W("eventLabel", "el"), Ab = W("eventValue", "ev"), ib = W("socialNetwork", "sn"), jb = W("socialAction", "sa"), kb = W("socialTarget", "st"), Ic = W("l1", "plt"), Jc = W("l2",
    "pdt"), Kc = W("l3", "dns"), Lc = W("l4", "rrt"), Mc = W("l5", "srt"), Nc = W("l6", "tcp"), Oc = W("l7", "dit"), Pc = W("l8", "clt"), Of = W("l9", "_gst"), Pf = W("l10", "_gbt"), Qf = W("l11", "_cst"), Rf = W("l12", "_cbt"), lb = W("timingCategory", "utc"), mb = W("timingVar", "utv"), nb = W("timingLabel", "utl"), Bb = W("timingValue", "utt"), pb = W("appName", "an"), qb = W("appVersion", "av", ""), rb = W("appId", "aid", ""), sb = W("appInstallerId", "aiid", ""), tb = W("exDescription", "exd"), Jb = W("exFatal", "exf"), zd = W("expId", "xid"), Ad = W("expVar", "xvar"), m = W("exp", "exp"),
    Dd = W("_utma", "_utma"), Ed = W("_utmz", "_utmz"), Fd = W("_utmht", "_utmht"), rc = W("_hc", void 0, 0), vc = W("_ti", void 0, 0), uc = W("_to", void 0, 20); Bc("dimension([0-9]+)", function (a) { return new Ac(a[0], "cd" + a[1]) }); Bc("metric([0-9]+)", function (a) { return new Ac(a[0], "cm" + a[1]) }); W("linkerParam", void 0, void 0, nd, Cc); var Sf = X("_cd2l", void 0, !1), oc = W("usage", "_u"), af = W("_um"); W("forceSSL", void 0, void 0, function () { return $b }, function (a, b, c) { F(34); $b = !!c }); var Zd = W("_j1", "jid"), ja = W("_j2", "gjid");
  Bc("\\&(.*)", function (a) { var b = new Ac(a[0], a[1]), c = kd(a[0].substring(1)); c && (L("Alias created: " + a[0] + " -> " + c), b.v = function (d) { return d.get(c) }, b.A = function (d, e, f, ea) { d.set(c, f, ea) }, b.i = void 0); return b });
  var Ob = X("_oot"), Vd = W("previewTask"), Pb = W("checkProtocolTask"), xd = W("validationTask"), Qb = W("checkStorageTask"), Gd = W("historyImportTask"), Rb = W("samplerTask"), Tb = W("_rlt"), Ub = W("buildHitTask"), Vb = W("sendHitTask"), Hd = W("ceTask"), we = W("devIdTask"), oe = W("timingTask"), Ce = W("displayFeaturesTask"), qa = W("customTask"), sf = W("fpsCrossDomainTask"), Gf = X("_cta"), T = X("name"), R = X("clientId", "cid"), n = X("clientIdTime"), Qd = X("storedClientId"), xe = W("userId", "uid"), U = X("trackingId", "tid"), ub = X("cookieName", void 0, "_ga"),
    S = X("cookieDomain"), vb = X("cookiePath", void 0, "/"), Cb = X("cookieExpires", void 0, 63072E3), Yd = X("cookieUpdate", void 0, !0), uf = X("cookieFlags", void 0, ""), wb = X("legacyCookieDomain"), Id = X("legacyHistoryImport", void 0, !0), xb = X("storage", void 0, "cookie"), Kb = X("allowLinker", void 0, !1), Lb = X("allowAnchor", void 0, !0), Db = X("sampleRate", "sf", 100), Eb = X("siteSpeedSampleRate", void 0, 1), Mb = X("alwaysSendReferrer", void 0, !1), la = X("_gid", "_gid"), na = X("_gcn"), ce = X("useAmpClientId"), ue = X("_gclid"), Ge = X("_gt"), Qe = X("_ge",
      void 0, 7776E6), Ve = X("_gclsrc"), We = X("storeGac", void 0, !0), bf = W("_x_19"), tf = W("_fplc", "_fplc"), E = X("_cs"), ff = X("_useUp", void 0, !1), Bf = W("up", "up"), Ie = W("_tac", void 0, !1), Hf = X("_gbraid"), If = X("_gbt"), Jf = X("_gbe", void 0, 7776E6), ac = [T, U, R, n, xe, ub, S, vb, Cb, Yd, uf, wb, Id, Kb, Lb, Db, Eb, Mb, xb, ce, We, ff, E], ob = W("transportUrl"), De = W("_r", "_r"), Ee = W("_slc", "_slc"), kf = W("_dp"), Nd = W("_jt", void 0, "n"), df = W("allowAdFeatures", void 0, !0), qf = W("allowAdPersonalizationSignals", void 0, !0);
  function Y(a, b, c, d) { b[a] = function () { try { return d && F(d), c.apply(this, arguments) } catch (e) { throw fc("exc", a, e && e.name), e; } } }; var od = function (a) { if ("cookie" == a.get(xb)) return a = Md("FPLC"), 0 < a.length ? a[0] : void 0 }, yf = function (a) { var b; if (b = V(a, bf) && a.get(Sf)) b = wf.get(a.get(Lb)), b = !(b && b._fplc); b && a.set(tf, od(a) || "0") }; var ba = function (a) { var b = Math.min(jc(a, Eb), 100); return ic(V(a, R)) % 100 >= b ? (L("Site speed data not sent - visitor sampled out"), !1) : !0 }, Sc = function (a) { var b = {}; if (qd(b) || rd(b)) { var c = b[Ic]; void 0 == c || Infinity == c || isNaN(c) ? L("Site speed data not sent - unsupported browser") : 0 < c ? (Rc(b, Kc), Rc(b, Nc), Rc(b, Mc), Rc(b, Jc), Rc(b, Lc), Rc(b, Oc), Rc(b, Pc), Rc(b, Of), Rc(b, Pf), Rc(b, Qf), Rc(b, Rf), ta(function () { a(b) }, 10)) : (L("Site speed data not available - waiting for onload"), Ca(Q, "load", function () { Sc(a) }, !1)) } else L("Site speed data not sent - unsupported browser") },
    qd = function (a) {
      var b = Q.performance || Q.webkitPerformance; b = b && b.timing; if (!b) return !1; var c = b.navigationStart; if (0 == c) return !1; a[Ic] = b.loadEventStart - c; a[Kc] = b.domainLookupEnd - b.domainLookupStart; a[Nc] = b.connectEnd - b.connectStart; a[Mc] = b.responseStart - b.requestStart; a[Jc] = b.responseEnd - b.responseStart; a[Lc] = b.fetchStart - c; a[Oc] = b.domInteractive - c; a[Pc] = b.domContentLoadedEventStart - c; a[Of] = Z.h - c; a[Pf] = Z.Ba - c; Q.google_tag_manager && Q.google_tag_manager._li && (b = Q.google_tag_manager._li, a[Qf] = b.cst, a[Rf] =
        b.cbt); return !0
    }, rd = function (a) { if (Q.top != Q) return !1; var b = Q.external, c = b && b.onloadT; b && !b.isValidLoadTime && (c = void 0); 2147483648 < c && (c = void 0); 0 < c && b.setPageReadyTime(); if (void 0 == c) return !1; a[Ic] = c; return !0 }, Rc = function (a, b) { var c = a[b]; if (isNaN(c) || Infinity == c || 0 > c) a[b] = void 0 }, ze = function (a) {
      return function (b) {
        if ("pageview" == b.get(Ma) && !a.L) {
          a.L = !0; var c = ba(b), d = 0 < aa(V(b, Pa), "gclid").length, e = 0 < aa(V(b, Pa), "wbraid").length; (c || d || e) && Sc(function (f) {
            c && a.send("timing", f); (d || e) && a.send("adtiming",
              f)
          })
        }
      }
    }; var Tc = !1, Yc = function (a) {
      if ("cookie" == V(a, xb)) {
        if (a.get(Yd) || V(a, Qd) != V(a, R)) { var b = 1E3 * jc(a, Cb); oa(a, R, ub, b); a.data.set(Qd, V(a, R)) } (a.get(Yd) || gd(a) != V(a, la)) && oa(a, la, na, 864E5); if (a.get(We)) {
          if (b = V(a, ue)) {
            var c = Math.min(jc(a, Qe), 1E3 * jc(a, Cb)); c = 0 === c ? 0 : Math.min(c, 1E3 * jc(a, Ge) + c - (new Date).getTime()); a.data.set(Qe, c); var d = {}, e = V(a, Ge), f = V(a, Ve), ea = Wc(V(a, vb)), l = Xc(V(a, S)), k = V(a, U), v = V(a, uf); f && "aw.ds" != f ? d && (d.xa = !0) : (b = ["1", e, Ae(b)].join("."), 0 <= c && (d && (d.wa = !0), pe("_gac_" + Ae(k), b, ea, l, k, c, v)));
            Ye(d)
          }
        } else F(75); a.get(We) && (b = V(a, Hf)) && (c = Math.min(jc(a, Jf), 1E3 * jc(a, Cb)), c = 0 === c ? 0 : Math.min(c, 1E3 * jc(a, If) + c - (new Date).getTime()), a.data.set(Jf, c), d = {}, v = V(a, If), ea = Wc(V(a, vb)), l = Xc(V(a, S)), k = V(a, U), a = V(a, uf), b = ["1", v, Ae(b)].join("."), 0 <= c && (d && (d.wa = !0), pe("_gac_gb_" + Ae(k), b, ea, l, k, c, a)), Mf(d))
      }
    }, oa = function (a, b, c, d) {
      var e = ie(a, b); if (e) {
        c = V(a, c); var f = Wc(V(a, vb)), ea = Xc(V(a, S)), l = V(a, uf), k = V(a, U); if ("auto" != ea) pe(c, e, f, ea, k, d, l) && (Tc = !0); else {
          F(32); for (var v = fd(), vf = 0; vf < v.length; vf++)if (ea =
            v[vf], a.data.set(S, ea), e = ie(a, b), pe(c, e, f, ea, k, d, l)) { N("Auto cookieDomain found: %s", ea); Tc = !0; return } O("Cookie write failed."); a.data.set(S, "auto")
        }
      }
    }, gd = function (a) { var b = Md(V(a, na)); return de(a, b) }, Zc = function (a) { if ("cookie" == V(a, xb) && !Tc && (Yc(a), !Tc)) throw N("Storage not available. Aborting hit."), "abort"; }, Kd = function (a) { if (a.get(Id)) { var b = V(a, S), c = V(a, wb) || Wb(), d = Jd("__utma", c, b); d && (F(19), a.set(Fd, (new Date).getTime(), !0), a.set(Dd, d.T), (b = Jd("__utmz", c, b)) && d.hash == b.hash && a.set(Ed, b.T)) } },
      ie = function (a, b) { b = Ae(V(a, b)); var c = Xc(V(a, S)).split(".").length; a = Vc(V(a, vb)); 1 < a && (c += "-" + a); return b ? ["GA1", c, b].join(".") : "" }, de = function (a, b) { return pa(b, V(a, S), V(a, vb)) }, pa = function (a, b, c) {
        if (!a || 1 > a.length) F(12); else {
          for (var d = [], e = 0; e < a.length; e++) {
            var f = a[e]; var ea = f.split("."); var l = ea.shift(); ("GA1" == l || "1" == l) && 1 < ea.length ? (f = ea.shift().split("-"), 1 == f.length && (f[1] = "1"), f[0] *= 1, f[1] *= 1, ea = { K: f, M: ea.join(".") }) : Cd.test(f) ? ea = { K: [0, 0], M: f } : (J("Unknown cookie version: " + l), ea = void 0); ea &&
              d.push(ea)
          } if (1 == d.length) return F(13), d[0].M; if (0 == d.length) F(12); else { F(14); d = sd(d, Xc(b).split(".").length, 0); if (1 == d.length) return d[0].M; d = sd(d, Vc(c), 1); 1 < d.length && F(41); return d[0] && d[0].M }
        }
      }, sd = function (a, b, c) { for (var d = [], e = [], f, ea = 0; ea < a.length; ea++) { var l = a[ea]; l.K[c] == b ? d.push(l) : void 0 == f || l.K[c] < f ? (e = [l], f = l.K[c]) : l.K[c] == f && e.push(l) } return 0 < d.length ? d : e }, Xc = function (a) { return 0 == a.indexOf(".") ? a.substr(1) : a }, fd = function () {
        var a = [], b = Wb().split("."); if (4 == b.length) {
          var c = b[b.length -
            1]; if (parseInt(c, 10) == c) return ["none"]
        } for (c = b.length - 2; 0 <= c; c--)a.push(b.slice(c).join(".")); b = I.location.hostname; Wd.test(b) || fe.test(b) || a.push("none"); return a
      }, Wc = function (a) { if (!a) return "/"; 1 < a.length && a.lastIndexOf("/") == a.length - 1 && (a = a.substr(0, a.length - 1)); 0 != a.indexOf("/") && (a = "/" + a); return a }, Vc = function (a) { a = Wc(a); return "/" == a ? 1 : a.split("/").length }, Ye = function (a) { a.wa && F(77); a.qa && F(74); a.sa && F(73); a.xa && F(69) }, Mf = function (a) { a.wa && F(85); a.qa && F(86); a.sa && F(87) }; function Jd(a, b, c) { "none" == b && (b = ""); var d = [], e = Md(a); a = "__utma" == a ? 6 : 2; for (var f = 0; f < e.length; f++) { var ea = ("" + e[f]).split("."); ea.length >= a && d.push({ hash: ea[0], T: e[f], ea: ea }) } if (0 != d.length) return 1 == d.length ? d[0] : Ld(b, d) || Ld(c, d) || Ld(null, d) || d[0] } function Ld(a, b) { if (null == a) var c = a = 1; else c = ic(a), a = ic(H(a, ".") ? a.substring(1) : "." + a); for (var d = 0; d < b.length; d++)if (b[d].hash == c || b[d].hash == a) return b[d] }; var vd = new RegExp(/^https?:\/\/([^\/:]+)/), wf = Q.google_tag_data.glBridge, wd = /(.*)([?&#])(?:_ga=[^&#]*)(?:&?)(.*)/, je = /(.*)([?&#])(?:_gac=[^&#]*)(?:&?)(.*)/; function nd(a) { if (a.get(Sf)) return F(35), wf.generate(Tf(a)); var b = V(a, R), c = V(a, la) || ""; b = "_ga=2." + P(ra(c + b, 0) + "." + c + "-" + b); (a = Uf(a)) ? (F(44), a = "&_gac=1." + P([ra(a.ta, 0), a.timestamp, a.ta].join("."))) : a = ""; return b + a }
  function ud(a, b) { var c = new Date, d = Q.navigator, e = d.plugins || []; a = [a, d.userAgent, c.getTimezoneOffset(), c.getYear(), c.getDate(), c.getHours(), c.getMinutes() + b]; for (b = 0; b < e.length; ++b)a.push(e[b].description); return ic(a.join(".")) } function ra(a, b) { var c = new Date, d = Q.navigator, e = c.getHours() + Math.floor((c.getMinutes() + b) / 60); return ic([a, d.userAgent, d.language || "", c.getTimezoneOffset(), c.getYear(), c.getDate() + Math.floor(e / 24), (24 + e) % 24, (60 + c.getMinutes() + b) % 60].join(".")) }
  var pd = function (a) { F(48); this.target = a; this.X = !1 }; pd.prototype.S = function (a, b) { if (a) { if (this.target.get(Sf)) return wf.decorate(Tf(this.target), a, b); if (a.tagName) { if ("a" == a.tagName.toLowerCase()) { a.href && (a.href = le(this, a.href, b)); return } if ("form" == a.tagName.toLowerCase()) return me(this, a) } if ("string" == typeof a) return le(this, a, b); O("Unknown Object passed to linker:decorate %s", a) } };
  var le = function (a, b, c) { var d = wd.exec(b); d && 3 <= d.length && (b = d[1] + (d[3] ? d[2] + d[3] : "")); (d = je.exec(b)) && 3 <= d.length && (b = d[1] + (d[3] ? d[2] + d[3] : "")); a = a.target.get("linkerParam"); d = b.indexOf("?"); var e = b.indexOf("#"); b = c ? b + ((-1 == e ? "#" : "&") + a) : -1 == e ? b + ((-1 === d ? "?" : "&") + a) : b.substring(0, e) + (-1 === d || d > e ? "?" : "&") + a + b.substring(e); b = b.replace(/&+_ga=/, "&_ga="); return b = b.replace(/&+_gac=/, "&_gac=") }, me = function (a, b) {
    if (b) if (b.action) if (N("Linker decorating form: %s", b), "get" == b.method.toLowerCase()) {
      a = a.target.get("linkerParam").split("&");
      for (var c = 0; c < a.length; c++) { var d = a[c].split("="), e = d[1]; d = d[0]; for (var f = b.childNodes || [], ea = !1, l = 0; l < f.length; l++)if (f[l].name == d) { f[l].setAttribute("value", e); ea = !0; break } ea || (f = I.createElement("input"), f.setAttribute("type", "hidden"), f.setAttribute("name", d), f.setAttribute("value", e), b.appendChild(f)) }
    } else "post" == b.method.toLowerCase() ? b.action = le(a, b.action) : O("Unknown form method %s on %s", b.method, b); else O("An action is required for the linker to work.")
  };
  pd.prototype.U = function (a, b, c) {
    function d(f) { try { f = f || Q.event; a: { var ea = f.target || f.srcElement; for (f = 100; ea && 0 < f;) { if (ea.href && ea.nodeName.match(/^a(?:rea)?$/i)) { var l = ea; break a } ea = ea.parentNode; f-- } l = {} } "http:" != l.protocol && "https:" != l.protocol || !ne(a, l.hostname || "") || (l.href && (l.href = le(e, l.href, b)), N("Link decorated: " + l.href)) } catch (k) { F(26) } } var e = this; this.target.get(Sf) ? wf.auto(function () { return Tf(e.target) }, a, b ? "fragment" : "", c) : (this.X || (this.X = !0, Ca(I, "mousedown", d, !1), Ca(I, "keyup", d, !1)),
      c && Ca(I, "submit", function (f) { f = f || Q.event; if ((f = f.target || f.srcElement) && f.action) { var ea = f.action.match(vd); ea && ne(a, ea[1]) && me(e, f) } }))
  }; pd.prototype.ca = function (a) { if (a) { var b = this, c = b.target.get(E); void 0 !== c && wf.passthrough(function () { if (c("analytics_storage")) return {}; var d = {}; return d._ga = b.target.get(R), d._up = "1", d }, 1, !0) } };
  function ne(a, b) { if (b == I.location.hostname) return !1; for (var c = 0; c < a.length; c++)if (a[c] instanceof RegExp) { if (a[c].test(b)) return !0 } else if (0 <= b.indexOf(a[c])) return !0; return !1 } function Xe(a, b) { return b != ud(a, 0) && b != ud(a, -1) && b != ud(a, -2) && b != ra(a, 0) && b != ra(a, -1) && b != ra(a, -2) } function Tf(a) { var b = Uf(a), c = {}; c._ga = a.get(R); c._gid = a.get(la) || void 0; c._gac = b ? [b.ta, b.timestamp].join(".") : void 0; b = a.get(tf); a = od(a); return c._fplc = b && "0" !== b ? b : a, c }
  function Uf(a) { function b(e) { return void 0 == e || "" === e ? 0 : Number(e) } var c = a.get(ue); if (c && a.get(We)) { var d = b(a.get(Ge)); if (1E3 * d + b(a.get(Qe)) <= (new Date).getTime()) F(76); else return { timestamp: d, ta: c } } }; var p = /^(GTM|OPT)-[A-Z0-9]+$/, xf = /^G-[A-Z0-9]+$/, q = /;_gaexp=[^;]*/g, r = /;((__utma=)|([^;=]+=GAX?\d+\.))[^;]*/g, ua = /^https?:\/\/[\w\-.]+\.google.com(:\d+)?\/optimize\/opt-launch\.html\?.*$/, w = function (a) { function b(d, e) { e && (c += "&" + d + "=" + P(e)) } var c = zf(a.type) + P(a.id); "dataLayer" != a.F && b("l", a.F); b("cx", a.context); b("t", a.target); b("cid", a.clientId); b("cidt", a.na); b("gac", a.oa); b("aip", a.la); a.sync && b("m", "sync"); b("cycle", a.J); a.ta && b("gclid", a.ta); ua.test(I.referrer) && b("cb", String(ae())); return c },
    Af = function (a, b) { var c = (new Date).getTime(); Q[a.F] = Q[a.F] || []; c = { "gtm.start": c }; a.sync || (c.event = "gtm.js"); Q[a.F].push(c); 2 === a.type && function (d, e, f) { Q[a.F].push(arguments) }("config", a.id, b) }, Cf = function (a, b, c, d) {
      c = c || {}; var e = 1; xf.test(b) && (e = 2); var f = { id: b, type: e, F: c.dataLayer || "dataLayer", J: !1 }, ea = void 0; a.get("&gtm") == b && (f.J = !0, O("Infinite loop detected. Tracker trying to load the container (%s) that created it. Ignoring require statement.", b)); 1 === e ? (f.la = !!a.get("anonymizeIp"), f.sync = d, b = String(a.get("name")),
        "t0" != b && (f.target = b), K(String(a.get("trackingId"))) || (f.clientId = String(a.get(R)), f.na = Number(a.get(n)), c = c.palindrome ? r : q, c = (c = I.cookie.replace(/^|(; +)/g, ";").match(c)) ? c.sort().join("").substring(1) : void 0, f.oa = c, f.ta = aa(V(a, Pa), "gclid"))) : 2 === e && (f.context = "c", ea = { allow_google_signals: a.get(df), allow_ad_personalization_signals: a.get(qf) }); Af(f, ea); return w(f)
    }; var Df = {}, Fe = function (a, b) { b || (b = (b = V(a, T)) && "t0" != b ? Pe.test(b) ? "_gat_" + Ae(V(a, U)) : "_gat_" + Ae(b) : "_gat"); this.aa = b }, Le = function (a, b) { var c = b.get(Ub); b.set(Ub, function (e) { Je(a, e, Zd); Je(a, e, ja); var f = c(e); Ke(a, e); return f }); var d = b.get(Vb); b.set(Vb, function (e) { var f = d(e); if (mf(e)) { F(80); var ea = { Y: lf(e, 1), google: lf(e, 2), count: 0 }; hf("https://stats.g.doubleclick.net/j/collect", ea.Y, ea); e.set(Zd, "", !0) } return f }) }, Je = function (a, b, c) {
      !1 !== b.get(df) && (b.get(c) ? J("Join id already set: " + c) : "1" == Md(a.aa)[0] ?
        b.set(c, "", !0) : b.set(c, "" + ae(), !0))
    }, Ke = function (a, b) { mf(b) && (N("Setting throttling cookie: %s", a.aa), pe(a.aa, "1", V(b, vb), V(b, S), V(b, U), 6E4, V(b, uf))) }, mf = function (a) { return !!a.get(Zd) && !1 !== a.get(df) }, Ff = function (a) { return !Df[V(a, U)] && void 0 === a.get("&gtm") && void 0 === a.get(ha) && void 0 === a.get(ob) && void 0 === a.get(bf) }, lf = function (a, b) {
      var c = new ef, d = function (f) { yc(f).i && c.set(yc(f).i, a.get(f)) }; d(Gc); d(Hc); d(U); d(R); d(Zd); 1 == b && (d(xe), d(ja), d(la)); !1 === a.get(qf) && c.set("npa", "1"); c.set(yc(oc).i, cf(a));
      var e = ""; c.map(function (f, ea) { e += P(f) + "="; e += P("" + ea) + "&" }); e += "z=" + ae(); 1 == b ? e = "t=dc&aip=1&_r=3&" + e : 2 == b && (e = "t=sr&aip=1&_r=4&slf_rd=1&" + e); return e
    }, Ef = function (a) { if (Ff(a)) return Df[V(a, U)] = !0, function (b) { if (b && !Df[b]) { var c = Cf(a, b); ye(c); Df[b] = !0 } } }, Pe = /^gtm\d+$/; var $d = function (a, b) { a = a.model; if (!a.get("dcLoaded")) { var c = new ec($e(a)); c.set(29); a.set(af, c.B); b = b || {}; var d; b[ub] && (d = Ae(b[ub])); b = new Fe(a, d); Le(b, a); a.set("dcLoaded", !0) } }; var Me = function (a) { if (!a.get("dcLoaded") && "cookie" == a.get(xb)) { var b = new Fe(a); Je(b, a, Zd); Je(b, a, ja); Ke(b, a); b = mf(a); var c = Ff(a); b && a.set(De, 1, !0); c && a.set(Ee, 1, !0); if (b || c) a.set(Nd, "d", !0), F(79), a.set(kf, { Y: lf(a, 1), google: lf(a, 2), Z: Ef(a), count: 0 }, !0) } }; var He = function () { var a = Q.gaGlobal = Q.gaGlobal || {}; return a.hid = a.hid || ae() }; var va = /^(UA|YT|MO|GP)-(\d+)-(\d+)$/, ad = function (a) {
      function b(e, f) { d.model.data.set(e, f) } function c(e, f) { b(e, f); d.filters.add(e) } var d = this; this.model = new wc; this.filters = new gc; L("Initializing tracker"); b(T, a[T]); b(U, xa(a[U])); b(ub, a[ub]); b(S, a[S] || Wb()); b(vb, a[vb]); b(Cb, a[Cb]); b(Yd, a[Yd]); b(uf, a[uf]); b(wb, a[wb]); b(Id, a[Id]); b(Kb, a[Kb]); b(Lb, a[Lb]); b(Db, a[Db]); b(Eb, a[Eb]); b(Mb, a[Mb]); b(xb, a[xb]); b(xe, a[xe]); b(n, a[n]); b(ce, a[ce]); b(We, a[We]); b(Sf, a[Sf]); b(bf, a[bf]); b(ff, a[ff]); b(E, a[E]); b(Gc, 1);
      b(Hc, "j91d"); c(Gf, Qc); c(Ob, kc); c(qa, Aa); c(Vd, Ud); c(Pb, lc); c(xd, ya); c(Qb, Zc); c(Gd, Kd); c(Rb, hc); c(Tb, qc); c(Hd, td); c(we, ve); c(Ce, Me); c(sf, yf); c(Ub, mc); c("_dt", nc); c(Vb, pc); c(oe, ze(this)); ke(this.model); qe(this.model, a[R]); this.model.set(yb, He()); Td(a); L("Initialization complete\n\n")
    }; ad.prototype.get = function (a) { G(a) || O("Please specify a field name to get its value."); return this.model.get(a) }; ad.prototype.set = function (a, b) { this.model.set(a, b) };
  ad.prototype.send = function (a) { L("Send start: " + Wf()); if (1 > arguments.length) O("No hit type specified. Aborting hit."); else { if ("string" === typeof arguments[0]) { var b = arguments[0]; var c = [].slice.call(arguments, 1) } else b = arguments[0] && arguments[0][Ma], c = arguments; b ? (c = Yb(Ze[b] || [], c), c[Ma] = b, this.model.set(c, void 0, !0), this.filters.H(this.model), L("Send finished: " + Wf()), this.model.data.u = {}) : O("No hit type specified. Aborting hit.") } };
  ad.prototype.pa = function (a, b) { var c = this; x(a, c, b) || (y(a, function () { x(a, c, b) }), z(String(c.get(T)), a, void 0, b, !0)) };
  var qe = function (a, b) {
    var c = V(a, ub); a.data.set(na, "_ga" == c ? "_gid" : c + "_gid"); if ("cookie" == V(a, xb)) {
      Tc = !1; c = Md(V(a, ub)); c = de(a, c); if (!c) { c = V(a, S); var d = V(a, wb) || Wb(); c = Jd("__utma", d, c); void 0 != c ? (F(10), d = c.ea[1] + "." + c.ea[2], Ga("Loaded legacy client id from utma cookie: %s (hash=%s)", d, c.hash), c = d) : c = void 0 } c && (Tc = !0); if (d = c && !a.get(Yd)) if (d = c.split("."), 2 != d.length) d = !1; else if (d = Number(d[1])) { var e = jc(a, Cb); d = d + e < (new Date).getTime() / 1E3 } else d = !1; d && (c = void 0, J("Client id is ignored because cookie update is disabled"));
      c && (a.data.set(Qd, c), a.data.set(R, c), (c = gd(a)) && a.data.set(la, c)); a.get(We) && (c = a.get(ue), d = a.get(Ve), !c || d && "aw.ds" != d) && (c = {}, d = (I ? Lf(c) : {})[V(a, U)], Ye(c), d && 0 != d.length && (c = d[0], a.data.set(Ge, c.timestamp / 1E3), a.data.set(ue, c.ta))); a.get(We) && !a.get(Hf) && (c = {}, d = (I ? Lf(c, "_gac_gb", !0) : {})[V(a, U)], Mf(c), d && 0 != d.length && (c = d[0], d = c.ta, c.labels && c.labels.length && (d += "." + c.labels.join(".")), a.data.set(If, c.timestamp / 1E3), a.data.set(Hf, d)))
    } if (a.get(Yd)) {
      c = ee("_ga", !!a.get(Lb)); var f = ee("_gl", !!a.get(Lb));
      d = wf.get(a.get(Lb)); e = d._ga; f && 0 < f.indexOf("_ga*") && !e && F(30); if (b || !a.get(ff)) f = !1; else if (f = a.get(E), void 0 === f || f("analytics_storage")) f = !1; else { F(84); a.data.set(Bf, 1); if (f = d._up) if (f = vd.exec(I.referrer)) { f = f[1]; var ea = I.location.hostname; f = ea === f || 0 <= ea.indexOf("." + f) || 0 <= f.indexOf("." + ea) ? !0 : !1 } else f = !1; f = f ? !0 : !1 } ea = d.gclid; var l = d._gac; if (c || e || ea || l) if (c && e && F(36), a.get(Kb) || rf(a.get(ce)) || f) {
        e && (Ga("Loaded client id: " + e), F(38), a.data.set(R, e), d._gid && (Ga("Loaded gid: " + d._gid), F(51), a.data.set(la,
          d._gid))); ea ? (F(82), a.data.set(ue, ea), d.gclsrc && a.data.set(Ve, d.gclsrc)) : l && (e = l.split(".")) && 2 === e.length && (F(37), a.data.set(ue, e[0]), a.data.set(Ge, e[1])); if (d = d._fplc) F(83), a.data.set(tf, d); if (c) b: if (e = c.indexOf("."), -1 == e) J("Invalid linker parameter format: " + c), F(22); else {
            ea = c.substring(0, e); f = c.substring(e + 1); e = f.indexOf("."); d = f.substring(0, e); f = f.substring(e + 1); if ("1" == ea) { if (e = f, Xe(e, d)) { J("Bad or expired linker parameter hash: " + c); F(23); break b } } else if ("2" == ea) {
              e = f.indexOf("-"); ea = ""; 0 <
                e ? (ea = f.substring(0, e), e = f.substring(e + 1)) : e = f.substring(1); if (Xe(ea + e, d)) { J("Bad or expired linker parameter hash: " + c); F(53); break b } ea && (Ga("Loaded gid: " + ea), F(2), a.data.set(la, ea))
            } else { J("Unrecognized linker parameter version: " + c); F(22); break b } Ga("Loaded client id: " + e); F(11); a.data.set(R, e); if (c = ee("_gac", !!a.get(Lb))) c = c.split("."), "1" != c[0] || 4 != c.length ? F(72) : Xe(c[3], c[1]) ? F(71) : (a.data.set(ue, c[3]), a.data.set(Ge, c[2]), F(70))
          }
      } else J("Linker disabled. Ignoring linker parameter: " + c), F(21)
    } b &&
      (Ga("Used client Id from constructor."), F(9), a.data.set(R, P(b))); a.get(R) || (b = (b = Q.gaGlobal) && b.from_cookie && "cookie" !== V(a, xb) ? void 0 : (b = b && b.vid) && -1 !== b.search(Bd) ? b : void 0, b ? (Ga("New visitor. Copying new clientId"), F(17), a.data.set(R, b)) : (Ga("New visitor. Generating new clientId"), F(8), a.data.set(R, ia()))); a.get(la) || (Ga("Generating new gid"), F(3), a.data.set(la, ia())); Yc(a); b = Q.gaGlobal = Q.gaGlobal || {}; c = V(a, R); a = c === V(a, Qd); if (void 0 == b.vid || a && !b.from_cookie) b.vid = c, b.from_cookie = a
  }, ke = function (a) {
    var b =
      Q.navigator, c = Q.screen, d = I.location, e = a.set; a: { var f = !!a.get(Mb), ea = !!a.get(ce); var l = I.referrer; if (/^(https?|android-app):\/\//i.test(l)) { if (f) break a; f = "//" + I.location.hostname; if (!Be(l, f)) { if (ea && (ea = f.replace(/\./g, "-") + ".cdn.ampproject.org", Be(l, ea))) { l = void 0; break a } break a } } l = void 0 } e.call(a, Qa, l); d && (e = d.pathname || "", "/" != e.charAt(0) && (F(31), e = "/" + e), a.set(Pa, d.protocol + "//" + d.hostname + e + d.search)); c && a.set(Xa, c.width + "x" + c.height); c && a.set(Wa, c.colorDepth + "-bit"); c = I.documentElement; l = (e =
        I.body) && e.clientWidth && e.clientHeight; ea = []; c && c.clientWidth && c.clientHeight && ("CSS1Compat" === I.compatMode || !l) ? ea = [c.clientWidth, c.clientHeight] : l && (ea = [e.clientWidth, e.clientHeight]); c = 0 >= ea[0] || 0 >= ea[1] ? "" : ea.join("x"); a.set(Ya, c); c = a.set; var k; if ((e = (e = Q.navigator) ? e.plugins : null) && e.length) for (l = 0; l < e.length && !k; l++)ea = e[l], -1 < ea.name.indexOf("Shockwave Flash") && (k = ea.description); if (!k) try { var v = new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7"); k = v.GetVariable("$version") } catch (vf) { } if (!k) try {
          v =
          new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6"), k = "WIN 6,0,21,0", v.AllowScriptAccess = "always", k = v.GetVariable("$version")
        } catch (vf) { } if (!k) try { v = new ActiveXObject("ShockwaveFlash.ShockwaveFlash"), k = v.GetVariable("$version") } catch (vf) { } k && (v = k.match(/[\d]+/g)) && 3 <= v.length && (k = v[0] + "." + v[1] + " r" + v[2]); c.call(a, Za, k || void 0); a.set(Ua, I.characterSet || I.charset); a.set(Ib, b && "function" === typeof b.javaEnabled && b.javaEnabled() || !1); a.set(Ta, (b && (b.language || b.browserLanguage) || "").toLowerCase()); a.data.set(ue,
          ee("gclid", !0)); a.data.set(Ve, ee("gclsrc", !0)); a.data.set(Ge, Math.round((new Date).getTime() / 1E3)); a.get(ue) || (a.data.set(Hf, ee("wbraid", !0)), a.data.set(If, Math.round((new Date).getTime() / 1E3))); if (d && a.get(Lb) && (b = I.location.hash)) {
            b = b.split(/[?&#]+/); d = []; for (k = 0; k < b.length; ++k)(H(b[k], "utm_id") || H(b[k], "utm_campaign") || H(b[k], "utm_source") || H(b[k], "utm_medium") || H(b[k], "utm_term") || H(b[k], "utm_content") || H(b[k], "gclid") || H(b[k], "dclid") || H(b[k], "gclsrc") || H(b[k], "wbraid")) && d.push(b[k]); 0 < d.length &&
              (b = "#" + d.join("&"), a.set(Pa, a.get(Pa) + b))
          }
  }, Ze = { pageview: [Ra], event: [fb, gb, hb, Ab], social: [ib, jb, kb], timing: [lb, mb, Bb, nb] }; var cd = function (a) { if ("prerender" == I.visibilityState) return !1; a(); return !0 }, A = function (a) { if (!cd(a)) { F(16); var b = !1, c = function () { if (!b && cd(a)) { b = !0; var d = c, e = I; e.removeEventListener ? e.removeEventListener("visibilitychange", d, !1) : e.detachEvent && e.detachEvent("onvisibilitychange", d) } }; Ca(I, "visibilitychange", c) } }; var gf = /^(?:(\w+)\.)?(?:(\w+):)?(\w+)$/, se = function (a) {
    this.G = a; if (t(a[0])) this.s = a[0]; else {
      var b = gf.exec(a[0]); null != b && 4 == b.length && (this.ja = b[1] || "t0", this.I = b[2] || "", this.methodName = b[3], this.fa = [].slice.call(a, 1), this.I || (this.D = "create" == this.methodName, this.g = "require" == this.methodName, this.ra = "provide" == this.methodName, this.$ = "remove" == this.methodName), this.g && (3 <= this.fa.length ? (this.da = this.fa[1], this.ba = this.fa[2]) : this.fa[1] && (G(this.fa[1]) ? this.da = this.fa[1] : this.ba = this.fa[1]))); b = a[1];
      var c = a[2]; if (!this.methodName) throw O("Invalid command: " + a), "abort"; if (this.g && (!G(b) || "" == b)) throw O("Invalid require command.", a), "abort"; if (this.ra && (!G(b) || "" == b || !t(c))) throw O("Invalid provide command.", a), "abort"; if (re(this.ja) || re(this.I)) throw O('Target name and plugin names should not contain "." or ":"'), "abort"; if (this.ra && "t0" != this.ja) throw O("Provide command should not be preceded by a tracker name."), "abort";
    }
  }; function re(a) { return 0 <= a.indexOf(".") || 0 <= a.indexOf(":") }; var Re, Se, Te, B; Re = new ef; Te = new ef; B = new ef; Se = { ec: 45, ecommerce: 46, linkid: 47 };
  var x = function (a, b, c) { var d = b == Z ? Fc : b.get(T), e = Re.get(a); if (!t(e)) return N("Waiting on require of %s to be fulfilled.", a), !1; b.plugins_ = b.plugins_ || new ef; if (b.plugins_.get(a)) return O("Command ignored. Plugin %s has already been required on tracker %s.", a, d), !0; b.plugins_.set(a, new e(b, c || {})); N("Plugin %s intialized on tracker %s.", a, d); return !0 }, z = function (a, b, c, d, e) {
    if (!t(Re.get(b)) && !Te.get(b)) {
      Se.hasOwnProperty(b) && F(Se[b]); a = Z.O(a); var f = void 0; if (p.test(b)) {
        F(52); if (!a) return !0; c = Cf(a.model,
          b, d, e); f = function () { O("Optimize container plugin %s failed to load", b); jf.H(["provide", b, function () { }]); var l = Q[d && d.dataLayer || "dataLayer"]; l && l.hide && t(l.hide.end) && l.hide[b] && (l.hide.end(), l.hide.end = void 0) }
      } !c && Se.hasOwnProperty(b) ? (F(39), c = b + ".js") : F(43); if (c) {
        if (a) { var ea = a.get(bf); G(ea) || (ea = void 0) } a = Ue(Kf(c, ea)); a = !ea || Xb(a.protocol) && C(a) ? a : Ue(Kf(c)); Xb(a.protocol) && C(a) ? (N("Loading resource for plugin: " + b), ye(a.url, void 0, e, void 0, f), Te.set(b, !0)) : O("Error loading resource for plugin %s: Refusing to load url: %s",
          b, a.url)
      } else N("No plugin url set for %s.", b)
    }
  }, y = function (a, b) { var c = B.get(a) || []; c.push(b); B.set(a, c) }, D = function (a, b) { Re.set(a, b); b = B.get(a) || []; for (var c = 0; c < b.length; c++)b[c](); B.set(a, []) }, C = function (a) {
    var b = Ue(I.location.href); if (H(a.url, zf(1)) || H(a.url, zf(2))) return !0; if (a.query || 0 <= a.url.indexOf("?") || 0 <= a.path.indexOf("://")) return !1; if (a.host == b.host && a.port == b.port) return !0; b = "http:" == a.protocol ? 80 : 443; return "www.google-analytics.com" == a.host && (a.port || b) == b && H(a.path, "/plugins/") ? !0 :
      !1
  }, Xb = function (a) { var b = I.location.protocol; return "https:" == a || a == b ? !0 : "http:" != a ? !1 : "http:" == b }, Ue = function (a) {
    function b(l) { var k = l.hostname || "", v = 0 <= k.indexOf("]"); k = k.split(v ? "]" : ":")[0].toLowerCase(); v && (k += "]"); v = (l.protocol || "").toLowerCase(); v = 1 * l.port || ("http:" == v ? 80 : "https:" == v ? 443 : ""); l = l.pathname || ""; H(l, "/") || (l = "/" + l); return [k, "" + v, l] } var c = I.createElement("a"); c.href = I.location.href; var d = (c.protocol || "").toLowerCase(), e = b(c), f = c.search || "", ea = d + "//" + e[0] + (e[1] ? ":" + e[1] : ""); H(a, "//") ?
      a = d + a : H(a, "/") ? a = ea + a : !a || H(a, "?") ? a = ea + e[2] + (a || f) : 0 > a.split("/")[0].indexOf(":") && (a = ea + e[2].substring(0, e[2].lastIndexOf("/")) + "/" + a); c.href = a; d = b(c); return { protocol: (c.protocol || "").toLowerCase(), host: d[0], port: d[1], path: d[2], query: c.search || "", url: a || "" }
  }, Kf = function (a, b) { return a && 0 <= a.indexOf("/") ? a : (b || Od(!1)) + "/plugins/ua/" + a }; var jf = { ka: function () { jf.j = [] } }; jf.ka(); jf.H = function (a) { var b = jf.N.apply(jf, arguments); b = jf.j.concat(b); for (jf.j = []; 0 < b.length;) { var c = b[0]; if (c.s) c = "ga(Function)"; else { for (var d = [], e = 0; c.G && e < c.G.length; e++)d.push(Fa(c.G[e])); c = "ga(" + d.join(", ") + ")" } dd("Running command: " + c); c = jf.R(b[0]); ge(); if (c) break; b.shift(); if (0 < jf.j.length) break } jf.j = jf.j.concat(b) };
  jf.N = function (a) { for (var b = [], c = 0; c < arguments.length; c++)try { var d = new se(arguments[c]); d.ra ? (D(d.fa[0], d.fa[1]), N("Registered new plugin: ga(provide, %s, Function)", d.fa[0])) : (d.g && (d.ha = z(d.ja, d.fa[0], d.da, d.ba)), b.push(d)) } catch (l) { var e = arguments[c], f = d, ea = l; sa(e) || t(e) ? sa(e) && !G(e[0]) ? O("First element of command array is not a string: %s", e) : f && f.g ? O("Invalid require command: %s", e) : O("Command failure: %s", ea) : O("Command is not an array or function: %s", ea) } return b };
  jf.R = function (a) {
    try {
      if (a.s) a.s.call(Q, Z.O("t0")); else {
        var b = a.ja == Fc ? Z : Z.O(a.ja); if (a.D) if ("t0" != a.ja) J('Command ignored. Use "create" instead of "%s.create"', a.ja); else { if (b = Z.create.apply(Z, a.fa), null === b) return !0 } else if (a.$) Z.remove(a.ja); else if (b) if (a.g) { if (a.ha && (a.ha = z(a.ja, a.fa[0], a.da, a.ba)), !x(a.fa[0], b, a.ba)) return !0 } else if (a.I) {
          var c = a.I, d = a.methodName, e = a.fa; b.plugins_ || O("Tracker does not have any plugins."); b.plugins_.get(c) || O("Tracker does not have %s plugin required.", c); var f =
            b.plugins_.get(c); f[d] || O("Plugin %s does not have method %s.", c, d); f[d].apply(f, e)
        } else b[a.methodName].apply(b, a.fa); else N("Command ignored. Unknown target: " + b)
      }
    } catch (ea) { c = ea, a.s ? O("Exception thrown from pushed function: %s", c) : a.g ? O("Error creating a plugin instance: %s", a.G) : a.ra ? O("Error registering a plugin: %s", a.G) : a.$ ? O("Error removing tracker: %s", a.G) : a.I ? O("Error calling a plugin method: %s", a.G) : O('Called method "%s" threw exception: %s', a.methodName, c) }
  }; var Z = function (a) { dd("Executing Google Analytics commands."); F(1); jf.H.apply(jf, [arguments]); ge() }; Z.o = {}; Z.C = []; Z.h = 0; Z.Ba = 0; Z.answer = 42; var pf = [U, S, T]; Z.create = function (a) { var b = Yb(pf, [].slice.call(arguments)); b[T] || (b[T] = "t0"); var c = "" + b[T]; if (Z.o[c]) return J("Ignoring create request for duplicate tracking name."), Z.o[c]; if (fa(b)) return null; N("Creating new tracker: " + c); b = new ad(b); Z.o[c] = b; Z.C.push(b); c = bd().tracker_created; if (t(c)) try { c(b) } catch (d) { J("Exception calling tracker_created: " + d) } return b };
  Z.remove = function (a) { for (var b = 0; b < Z.C.length; b++)if (Z.C[b].get(T) == a) { N("Removing tracker: " + a); Z.C.splice(b, 1); Z.o[a] = null; return } O("Tracker does not exist.") }; Z.O = function (a) { return Z.o[a] }; Z.getAll = function () { return Z.C.slice(0) };
  Z.P = function () {
    dd("Initializing Google Analytics."); "ga" != Fc && F(49); var a = Q[Fc]; if (a && 42 == a.answer) J("Tracking script already loaded. Abandoning initialization."); else {
      a && 42 != a.answer && !a.q && J("An existing object with the name '%s' found. Unexpected results can occur because of this.", Fc); Z.h = a && a.l; Z.Ba = 1 * new Date; Z.loaded = !0; var b = Q[Fc] = Z; Y("create", b, b.create); Y("remove", b, b.remove); Y("getByName", b, b.O, 5); Y("getAll", b, b.getAll, 6); Y("dump", b, b.dump); b = ad.prototype; Y("get", b, b.get, 7); Y("set", b, b.set,
        4); Y("send", b, b.send); Y("requireSync", b, b.pa); b = wc.prototype; Y("get", b, b.get); Y("set", b, b.set); if ("https:" != I.location.protocol && !$b) { a: { b = I.getElementsByTagName("script"); for (var c = 0; c < b.length && 100 > c; c++) { var d = b[c].src; if (d && 0 == d.indexOf(Od(!0) + "/analytics")) { b = !0; break a } } b = !1 } b && (L("Analytics.js is secure, forcing SSL for all hits."), $b = !0) } (Q.gaplugins = Q.gaplugins || {}).Linker = pd; b = pd.prototype; D("linker", pd); Y("decorate", b, b.S, 20); Y("autoLink", b, b.U, 25); Y("passthrough", b, b.ca, 25); D("displayfeatures",
          $d); D("adfeatures", $d); a = a && a.q; sa(a) ? jf.H.apply(Z, a) : F(50)
    } ge()
  };
  Z.ga = function () {
    for (var a = Z.getAll(), b = 0; b < a.length; b++)dd("Tracker: " + a[b].get(T)), Ja(a[b].model), ge(); a = I.cookie; dd("Cookie Information"); a = a.split("; "); b = [["Name", "Domain", "Path", "Value"]]; for (var c = 0; c < a.length; c++) {
      var d = a[c].split("="), e = d[0], f = d[1] || ""; if (Zb(tc, e)) { d = b; for (var ea = d.push, l = "", k = f.split(".")[0], v = fd(), vf = 0; vf < v.length; vf++) { if (k == ic(v[vf])) { l = v[vf]; break } if (k == ic("." + v[vf])) { l = v[vf]; break } } ea.call(d, [e, l, "/", f]) } else if ("_ga" == e) {
        l = ""; d = "/"; if (ea = f.split(".")[1]) ea = ea.split("-"),
          l = I.location.hostname.split("."), l = l.slice(l.length - ea[0]).join("."), d += I.location.pathname.split("/").slice(1, Number(ea[1] || 1)).join("/"); b.push([e, l, d, f])
      } else /^((__utmt)|(_gat))/.test(e) && b.push([e, "", "", f])
    } Xd(b); ge()
  }; Z.dump = Z.ga; Ga("\n                         _                          _       _   _\n                        | |                        | |     | | (_)\n  __ _  ___   ___   __ _| | ___    __ _ _ __   __ _| |_   _| |_ _  ___ ___\n / _` |/ _ \\ / _ \\ / _` | |/ _ \\  / _` | '_ \\ / _` | | | | | __| |/ __/ __|\n| (_| | (_) | (_) | (_| | |  __/ | (_| | | | | (_| | | |_| | |_| | (__\\__ \\\n \\__, |\\___/ \\___/ \\__, |_|\\___|  \\__,_|_| |_|\\__,_|_|\\__, |\\__|_|\\___|___/\n  __/ |             __/ |                              __/ |\n |___/             |___/                              |___/\n");
  J("Running analytics_debug.js. This script is intended for testing and debugging only."); var Xf = Z.P, Yf = Q[Fc]; Yf && Yf.r ? Xf() : A(Xf); A(function () { jf.H(["provide", "render", Aa]) });
})(window);